language: node_js
node_js:
  - '14'
addons:
  chrome: stable
branches:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
      - hspichardo@gmail.com
script:
  - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - ng e2e --protractor-config=e2e/protractor-travis.conf.js
deploy:
  provider: heroku
  api_key:
    secure: 11bd6cab-4ef6-4dfe-b5f6-422ff91c58a9
  on:
    branch: master
  app: toberuman
